After review

diff --git a/.github/workflows/deploy-new-version.yml b/.github/workflows/deploy-new-version.yml
--- a/.github/workflows/deploy-new-version.yml
+++ b/.github/workflows/deploy-new-version.yml
@@ -7,7 +7,7 @@ on:
 
   push:
     branches:
-      - workflows
+      - main
 
   workflow_dispatch:
     inputs:
@@ -17,11 +17,38 @@ on:
         default: 'latest'
 
 jobs:
-  check-version:
-    if: ${{ github.ref_name == 'main' && inputs.version != '' }}
+  format_and_lint:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: '16.14.2'
+
+      - name: Install Dependencies
+        run: npm ci
+
+      - name: Run ESLint
+        run: npm run lint
+
+      - name: Run Prettier
+        run: npm run prettier
+
+  check-version:
+    runs-on: ubuntu-latest
+    needs: format_and_lint
+
+    steps:
+      - name: Should continue
+        run: |
+          if [[ ${{ github.ref_name == 'main' && inputs.version != '' }} ]]; then
+            exit 0
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -29,6 +56,23 @@ jobs:
         run: |
           git config user.name "${GITHUB_ACTOR}"
           git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+
+      - name: Install semver
+        run: npm install semver
+
+      - name: Get current version
+        id: get_version
+        run: echo "current_version=$(jq -r '.version' package.json)" >> $GITHUB_ENV
+
+      - name: Validate and set new version
+        run: |
+          new_version="${{ inputs.version }}"
+          current_version="${{ env.current_version }}"
+
+          if npx semver $new_version -r "<=$current_version"; then
+            echo "Error: New version ($new_version) is lowest or the same as current ($current_version)"
+            exit 1
+          fi
 
       - name: Bump version
         run: |
@@ -41,6 +85,7 @@ jobs:
 
   prepare-matrix:
     runs-on: ubuntu-latest
+    needs: [format_and_lint, check-version]
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
@@ -48,9 +93,9 @@ jobs:
         id: set-matrix
         run: |
           if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "matrix={\"include\":[{\"build-type\":\"production\",\"tag_suffix\":\"production\",\"environment\":\"production-fidl\"}, {\"build-type\":\"staging\",\"tag_suffix\":\"stg\",\"environment\":\"staging-fidl\"}]}" >> $GITHUB_OUTPUT
+            echo "matrix={\"include\":[{\"build-type\":\"production\",\"environment\":\"production-fidl\"}, {\"build-type\":\"staging\",\"tag_suffix\":\"stg\",\"environment\":\"staging-fidl\"}]}" >> $GITHUB_OUTPUT
           else
-            echo "matrix={\"include\":[{\"build-type\":\"staging\",\"tag_suffix\":\"staging\",\"environment\":\"staging-fidl\"}]}" >> $GITHUB_OUTPUT  
+            echo "matrix={\"include\":[{\"build-type\":\"staging\",\"environment\":\"staging-fidl\"}]}" >> $GITHUB_OUTPUT  
           fi
 
   ReuseableMatrixJobForDeployment:
@@ -61,6 +106,5 @@ jobs:
     uses: ./.github/workflows/release-new-version.yml
     with:
       version: ${{ inputs.version }}
-      tag_suffix: ${{ matrix.tag_suffix }}
       environment: ${{ matrix.environment }}
     secrets: inherit
